# FROM php:8.2-cli-alpine3.20
FROM php:8.2.26-fpm-alpine

COPY --from=composer/composer:2-bin /composer /usr/local/bin/composer

COPY composer.json /app/composer.json
COPY composer.lock /app/composer.lock

WORKDIR /app

RUN composer install